openapi: 3.0.3
info:
  title: Health Check API
  version: 1.0.0
  description: |
    システムの Readiness/Liveness を確認するためのヘルスチェック API

tags:
  - name: Health
    description: ヘルスチェック関連のエンドポイント

paths:
  /health/readiness:
    get:
      tags:
        - Health
      summary: Readiness チェック
      description: システムがリクエストを受け付ける準備ができているかを確認します
      responses:
        '200':
          description: システムが利用可能
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          description: システムが利用不可
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

  /health/liveness:
    get:
      tags:
        - Health
      summary: Liveness チェック
      description: システムが正常に動作しているかを確認します
      responses:
        '200':
          description: システムが稼働中
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          description: システムが停止またはハングアップ中
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'

components:
  schemas:
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          description: システムの状態
          enum:
            - available
            - unavailable
      required:
        - status
      example:
        status: available
