# https://taskfile.dev
# https://github.com/go-task/task
version: '3'

vars: {}

tasks:
  devcontainer_build:
    cmds:
      - ./scripts/devcontainer_build.sh
    silent: true

  docker_build:
    cmds:
      - ./scripts/docker_build.sh
    silent: true

  docker_compose_down:
    cmds:
      - ./scripts/docker_compose_down.sh
    silent: true

  docker_compose_run_k6:
    cmds:
      - ./scripts/docker_compose_run_k6.sh
    silent: true

  docker_compose_run_migrate_down:
    cmds:
      - ./scripts/docker_compose_run_migrate_down.sh
    silent: true

  docker_compose_run_migrate_up:
    cmds:
      - ./scripts/docker_compose_run_migrate_up.sh
    silent: true

  docker_compose_up:
    cmds:
      - ./scripts/docker_compose_up.sh
    silent: true

  gitingest:
    cmds:
      - ./scripts/gitingest.sh
    silent: true

  golangci-lint:
    cmds:
      - ./scripts/golangci-lint.sh
    silent: true

  go_mod_tidy:
    cmds:
      - ./scripts/go_mod_tidy.sh
    silent: true

  oapi-codegen:
    cmds:
      - ./scripts/oapi-codegen.sh
    silent: true

  prettier:
    cmds:
      - ./scripts/prettier.sh
    silent: true

  redocly_join:
    cmds:
      - ./scripts/redocly_join.sh
    silent: true

  remove_ds_store:
    cmds:
      - ./scripts/remove_ds_store.sh
    silent: true

  renovate_dry_run:
    cmds:
      - ./scripts/renovate_dry_run.sh
    silent: true

  renovate_validate_config:
    cmds:
      - ./scripts/renovate_validate_config.sh
    silent: true

  sqlc:
    cmds:
      - ./scripts/sqlc.sh
    silent: true
