postgres:
  host: postgres
  port: 5432
  user: postgres
  password: hogehoge
  database: test_db
  sslmode: disable
valkey:
  host: valkey
  port: 6379
tempo:
  host: tempo
  port: 4318
pyroscope:
  host: pyroscope
  port: 4040
