# config/opentelemetry-collector/config.yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318 # OTLP/HTTP 受信

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1024
  batch:
    send_batch_size: 8192
    timeout: 5s

exporters:
  # Logs → Loki
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  # Metrics → Alloy (→ Mimir)
  otlphttp/alloy:
    endpoint: http://alloy:4318
    tls:
      insecure: true

  # Traces → Tempo
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true

  # Profiles → Pyroscope  (OTLP/HTTP)
  otlphttp/pyroscope:
    endpoint: http://pyroscope:4040/otlp
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/loki]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/alloy]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/tempo]

    profiles: # α段階
      receivers: [otlp]
      exporters: [otlphttp/pyroscope]
